# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6bc4843c-c193-4c4b-ae9a-5107d9baed80";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6bc4843c-c193-4c4b-ae9a-5107d9baed80".device = "/dev/disk/by-uuid/6bc4843c-c193-4c4b-ae9a-5107d9baed80";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/50AC-A46A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ #{ device = "/dev/mapper/luks-ebed38ca-90ed-4b1e-ad75-d0b86d842659"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
